### ISSUE TITLE
Unable to compile

### ISSUE THREAD

**Issue by JakSparro98** [rburing/physics_server_box2d#2]
**Platform:** windows 10
**Godot version:** 4.0.stable.mono

I've tried to swap the original godot-cpp with the [current one](https://github.com/godotengine/godot-cpp/tree/9d1c396c54fc3bdfcc7da4f3abcb52b14f6cce8f) since the beta9 one crashes the engine, but it fails, throwing compiler error C3668 and sometimes C2555 at almost every box2d classes.

I'm not an expert but I've done a test to study the behavior and to make sure it's not something I'm doing wrong, I've re downloaded the beta9 version (same commit of the original) and the compilation passed.

Here a couple of lines at the end of the scons compilation attempt:

 ```
C:\godotDev\box2d_extension\godot-cpp\test\src\physics_server_box2d.h(92): error C3668: 'PhysicsServerBox2D::_body_get_shape': method with override specifier 'override' did not override any base class methods
C:\godotDev\box2d_extension\godot-cpp\test\src\physics_server_box2d.h(93): error C3668: 'PhysicsServerBox2D::_body_get_shape_transform': method with override specifier 'override' did not override any base class methods
C:\godotDev\box2d_extension\godot-cpp\test\src\physics_server_box2d.h(94): error C3668: 'PhysicsServerBox2D::_body_remove_shape': method with override specifier 'override' did not override any base class methods
C:\godotDev\box2d_extension\godot-cpp\test\src\physics_server_box2d.h(97): error C3668: 'PhysicsServerBox2D::_body_attach_object_instance_id': method with override specifier 'override' did not override any base class methods
C:\godotDev\box2d_extension\godot-cpp\test\src\physics_server_box2d.h(98): error C2555: 'PhysicsServerBox2D::_body_get_object_instance_id': overriding virtual function return type differs and is not covariant from 'godot::PhysicsServer2DExtension::_body_get_object_instance_id'
C:\godotDev\box2d_extension\godot-cpp\gen\include\godot_cpp/classes/physics_server2d_extension.hpp(129): notes: see declaration of 'godot::PhysicsServer2DExtension::_body_get_object_instance_id'
scons: *** [src\register_types.windows.template_debug.x86_64.obj] Error 2
scons: building terminated because of errors.
```

**Comment by rburing** [comment]
Thanks for testing! I've just updated `master` to compile for Godot 4.0-stable: https://github.com/rburing/physics_server_box2d/commit/08317799c1a7ab61ab4a26efe84e87e8f708a226.

Some GDExtension API changes (64-bit integers to 32-bit integers) caused those errors you mentioned; they are fixed now.

While the project does compile now, it remains in very early stages of development.
